verif presence model

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,6 +21,10 @@
             - name: Restore model file
               run: |
                 curl -o src/crop_ticket/model_complet.pth "https://storage.googleapis.com/kadi_model_ticket/model_complet.pth"
+
+            - name: Verify model file
+              run: |
+                test -f src/crop_ticket/model_complet.pth || { echo "Model file is missing!"; exit 1; }
         
             - name: Set up Cloud SDK
               uses: google-github-actions/setup-gcloud@v1
